title: FlutPulse
description: Fix Flutter issues with clear, practical solutions.
theme: jekyll-theme-primer
permalink: /articles/:title.html
remote_theme: null
plugins:
  - jekyll-archives

jekyll-archives:
  enabled:
    - categories
  layout: category-page
  permalinks:
    category: /categories/:name/

formspree_endpoint: "https://formspree.io/f/xdenlvqd"
future: false
