title: FlutPulse
description: Fix Flutter issues with clear, practical solutions.
theme: jekyll-theme-primer
permalink: /articles/:title.html
remote_theme: null
plugins:
  - jekyll-archives

jekyll-archives:
  enabled:
    - categories
  layout: category-page
  permalinks:
    category: /categories/:name/

web3forms_access_key: "75d4a52b-a44b-4725-98c8-8d44b5d8c641"
future: false
